server:
  port: 8080
#spring:
#  security:
#    user:
#      name: user
#      password: 123456

dex:
  clientId: dex_jingrui
  clientSecret: QACCDTXXTTBLNMSWQCHXNV
  scope: all
  rootUrl: https://www.fgconsulting.cn:10106
