server:
  port: 8080
#spring:
#  security:
#    user:
#      name: user
#      password: 123456

dex:
  clientId: dex_some_client
  clientSecret: dex_some_secret
  scope: all
  rootUrl: http://localhost:10106
